"""empty message

Revision ID: 41cd81c7f0dc
Revises: 6849c1c8fc68
Create Date: 2018-10-28 17:43:48.419844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41cd81c7f0dc'
down_revision = '6849c1c8fc68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'waves', ['default_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_team_id')
    # ### end Alembic commands ###
