"""empty message

Revision ID: b5f1123049c2
Revises: 41cd81c7f0dc
Create Date: 2018-10-28 17:57:41.978870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f1123049c2'
down_revision = '41cd81c7f0dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_default_team_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'teams', ['default_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_default_team_id_fkey', 'users', 'waves', ['default_team_id'], ['id'])
    # ### end Alembic commands ###
